FROM python:3.9-slim

WORKDIR /app

COPY mock_notification_receiver.py /app/
COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

VOLUME /app/logs

CMD ["python", "mock_notification_receiver.py"]
